### ISSUE TITLE
有个小问题~

### ISSUE THREAD

**Issue by lazyhero** [jzlxiaohei/webpack-coc#1]
在执行构建最后 终端输出如下提示 如果要更换这些被弃用的配置项 在哪做更改呢
The unused option is deprecated. Please use options.discardUnused instead.
The urls option is deprecated. Please use options.normalizeUrl instead.
The idents option is deprecated. Please use options.mergeIdents instead.
The idents option is deprecated. Please use options.reduceIdents instead.

**Comment by jzlxiaohei** [comment]
tks.`css-loader`升级到0.17.0就好。 详见这个 [issue](https://github.com/webpack/css-loader/issues/126)
