### ISSUE TITLE
externals 作用

### ISSUE THREAD

**Issue by zhangping2014** [jzlxiaohei/webpack-coc#2]
很开心找到了这个多页面的构建分享，externals 这个配置不太明白。方便讲解下吗。
externals:{
        'react': {
            root: 'React',
            commonjs2: 'react',
            commonjs: 'react',
            amd: 'react'
        },
        'jquery': {
            root: 'jQuery',
            commonjs2: 'jquery',
            commonjs: 'jquery',
            amd: 'jquery'
        },
        'react-dom':{
            root:'ReactDOM',
            commonjs2: 'react-dom',
            commonjs: 'react-dom',
            amd:'react-dom'
        }
        //'wscn-common':{
        //    commonjs2:'wscn-common',
        //    commonjs:'wscn-common'
        //}
    },

**Comment by jzlxiaohei** [comment]
具体的见[文档](https://webpack.github.io/docs/library-and-externals.html)

我稍微讲下思路

>externals allows you to specify dependencies for your library that are not resolved by webpack, but become dependencies of the output. This means they are imported from the environment during runtime.

不然你页面里，都有这样的代码

       import React form 'react'

react 很大，所以不想开发的时候，每次都解析react的代码。另外真正发布，有可能希望直接用cdn。这就告诉webpack，这个东西到时候会提供，构建的时候不要管它。这样你构建的代码，是没有react的内容。

不过demo里的lib，就是要打包这些东西，所以构建lib的时候不能externals

至于root,commonjs,commonjs2，是这些lib在不同规范下的形式。比如jquery，全局变量一般是jQuery,但是node环境里，

         var $ = require('jquery');

这是中比较麻烦但是很全面的写法，大部分情况,先cdn引用他们，都是暴露到window对象上的，直接类似下面的写法一般就ok了

     externals: {
        // require("jquery") is external and available
        //  on the global var jQuery
        "jquery": "jQuery"，
        "react":"React"
     }

**Comment by zhangping2014** [comment]
基本上明白了，相当于如果在页面上var $ =  require('jquery') 就等于调用了window.jQuery是吧

**Comment by jzlxiaohei** [comment]
恩。不过不是页面，是webpack 管理的js文件。
