### ISSUE TITLE
关于webpack.optimize.CommonsChunkPlugin

### ISSUE THREAD

**Issue by zhangping2014** [jzlxiaohei/webpack-coc#3]
![image](https://cloud.githubusercontent.com/assets/6504135/10997362/805314d0-84c7-11e5-89b5-ab1edd72afee.png)
对于CommonsChunkPlugin 看过文档了，英文不太好，读得不是太明白。
只会用提取一个commjs出来。不知道您这种写法有什么好处吗，方便给解释下吗

**Comment by jzlxiaohei** [comment]
这个插件就是提取公共部分。如果要提取多个，就要有多个插件，可参考[example](                                https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks
)。不过老实说，多commons的构建，我还没实践过。

这里的构建，只考虑构建出一个commons。

至于为什么写成这样，文章里都有说，默认当模块被引用>=3c次时，这个插件就认为模块是公共的。这样写，就是给工程师一个自主控制的机会，通过文件命名，强制某个模块是公共的，或者不公共的

还有，文档不看不行。我遇到过各种坑，后来发现文档里都有。webpack的配置很复杂，不反复看文档，会遇到各种坑，爬不出去

**Comment by zhangping2014** [comment]
非常感谢， 对于英文不好得人来说文档看着很头大，一直搞不明白。
